Handles running .EXEs on WSL

diff --git a/aliases b/aliases
--- a/aliases
+++ b/aliases
@@ -57,6 +57,36 @@ fi
 # some useful commands
 source ~/Repos/env/dotfiles/lib/unix_utils.sh
 
+# Windows WSL-specific
+if [ `uname -r | sed -n 's/.*\( *Microsoft *\).*/\1/p'` = 'Microsoft' ]; then
+  export WSL=1
+
+  # when a command is not found, tries to find an executable with the same name and run it
+  command_not_found_handle() {
+    if cmd.exe /c "(where $1 || (help $1 |findstr /V Try)) >nul 2>nul && ($* || exit 0)"; then
+        return $?
+    else
+        if [ -x /usr/lib/command-not-found ]; then
+           /usr/lib/command-not-found -- "$1"
+           return $?
+        elif [ -x /usr/share/command-not-found/command-not-found ]; then
+           /usr/share/command-not-found/command-not-found -- "$1"
+           return $?
+        else
+           printf "%s: command not found\n" "$1" >&2
+           return 127
+        fi
+    fi
+  }
+
+  # does the same, but for ZSH
+  command_not_found_handler() {
+    command_not_found_handle "$@"
+    return $?
+  }
+fi
+
+
 if [ -d "$HOME/Repos/ruby/danbooru-ruby-grabber" ]; then
   source ~/Repos/ruby/danbooru-ruby-grabber/aliases
 fi
